export const SHOW_TRAVELLERS_PAGE = 'SHOW_TRAVELLERS_PAGE'
export const SHOW_AIR_SHARING_PAGE = 'SHOW_AIR_SHARING_PAGE'
export const SHOW_REGION_PAGE = 'SHOW_REGION_PAGE'
export const SHOW_RESOURCES_PAGE = 'SHOW_RESOURCES_PAGE'
export const SHOW_CONTAINER_SHARING_PAGE = 'SHOW_CONTAINER_SHARING_PAGE'
export const SHOW_NEWS_EVENTS_PAGE = 'SHOW_NEWS_EVENTS_PAGE'
export const LEAVE_ALL_PAGES = 'LEAVE_ALL_PAGES'

export const SELECT_LOADS = 'SELECT_LOADS'
export const SELECT_TRIPS = 'SELECT_TRIPS'

export const SHOW_WINDOW_AND_BACKDROP = 'SHOW_WINDOW_AND_BACKDROP'
export const HIDE_WINDOW_AND_BACKDROP = 'HIDE_WINDOW_AND_BACKDROP'

export const SHOW_USER_INFO = 'SHOW_USER_INFO'
export const HIDE_USER_INFO = 'HIDE_USER_INFO'
export const SHOW_ITEM_WEIGHT_IN_KG = 'SHOW_ITEM_WEIGHT_IN_KG'
export const SHOW_ITEM_WEIGHT_IN_LBS = 'SHOW_ITEM_WEIGHT_IN_LBS'

export const SELECT_AVATAR = 'SELECT_AVATAR'
export const CROP_AVATAR = 'CROP_AVATAR'
export const CHANGE_PHOTO_SCALE = 'CHANGE_PHOTO_SCALE'

export const SHOW_FILTERS_BLOCK = 'SHOW_FILTERS_BLOCK'
export const HIDE_FILTERS_BLOCK = 'HIDE_FILTERS_BLOCK'